# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-06-23 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sokol', '0002_auto_20200619_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('user_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sokol.UserProfile')),
            ],
        ),
    ]
