# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-06-23 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sokol', '0003_lastonline'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LastOnline',
            new_name='Status',
        ),
    ]
