# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-06-23 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sokol', '0004_auto_20200623_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
