# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-06-23 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sokol', '0005_ab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ab',
        ),
    ]
