# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-06-23 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sokol', '0006_delete_ab'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='user_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='sokol.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
